[package]
name = "beigebox"
version = "0.1.0"
edition = "2024"

[dependencies]
beigebox_database = { path = "beigebox_database" }

rocket = { version = "0.5.1", features = ["secrets"] }
maud = { version = "0.27.0", features = ["rocket"] }
bincode = { version = "2.0.1" }