[package]
name = "wisp_pages"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
wisp_database = { path = "../wisp_database" }
wisp_session_manager = { path = "../wisp_session_manager" }

maud = { version = "0.27.0" }